/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountRow: typeof import('./src/components/AccountRow.vue')['default']
    Allert: typeof import('./src/components/Allert.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
  }
}
